spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/springboot-mybatis?useUnicode=true&characterEncoding=utf-8
        password: root
        username: root
    jpa:
        hibernate:
            ddl-auto: update
            naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
        properties:
            hibernate.globally_quoted_identifiers: true
            hibernate.show_sql: false
            hibernate.format_sql: true

    # 增加rabbitmq的连接信息
    rabbitmq:
        host: localhost
        port: 5672
        username: springcloud
        password: springcloud
        queueName: spring-boot
        exchange: spring-boot-exchange